const data = [{
        id: 1,
        category: "cannondale",
        year: 2019,
        img1: "../images/bike1.jpg",
        img2: "",
        img3: "",
        title: "ADVENTURE NEO 1 EQ",
        description: "Una bici elettrica ideale per andare a lavoro e godersi le caratteristiche stradine di campagna",
        tag: "e-bike corsa",
        taglia: "s m l xl",
        colori: "+4",
        prezzo: "4.000,00",
        isDiscount: true,
        discountPrice: "3.900,00",
        isCompare: false,
    },
    {},
    {},
    {},
];