const data = [{
        id: 1,
        category: "cannondale",
        year: 2019,
        img1: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        img2: "https://m.media-amazon.com/images/I/61hzbxbJW2L._AC_SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        title: "ADVENTURE NEO 1 EQ",
        description: "Una bici elettrica ideale per andare a lavoro e godersi le caratteristiche stradine di campagna",
        tag: "e-bike corsa",
        taglia: "s m l xl",
        colori: "+4",
        prezzo: "4.000,00",
        isDiscount: true,
        discountPrice: "3.900,00",
        isCompare: false,
        state: "usato",
    },
    {
        id: 2,
        category: "cannondale",
        year: 2019,
        img1: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        img2: "https://m.media-amazon.com/images/I/61hzbxbJW2L._AC_SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        title: "ADVENTURE NEO 1 EQ",
        description: "Una bici elettrica ideale per andare a lavoro e godersi le caratteristiche stradine di campagna",
        tag: "e-bike corsa",
        taglia: "s m l xl",
        colori: "+4",
        prezzo: "4.000,00",
        isDiscount: true,
        discountPrice: "3.900,00",
        isCompare: false,
        state: "nuovo",
    },
    {
        id: 3,
        category: "cannondale",
        year: 2019,
        img1: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        img2: "https://m.media-amazon.com/images/I/61hzbxbJW2L._AC_SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        title: "ADVENTURE NEO 1 EQ",
        description: "Una bici elettrica ideale per andare a lavoro e godersi le caratteristiche stradine di campagna",
        tag: "e-bike corsa",
        taglia: "s m l xl",
        colori: "+4",
        prezzo: "4.000,00",
        isDiscount: true,
        discountPrice: "3.900,00",
        isCompare: false,
        state: "nuovo",
    },
    {
        id: 4,
        category: "cannondale",
        year: 2019,
        img1: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        img2: "https://m.media-amazon.com/images/I/61hzbxbJW2L._AC_SY355_.jpg",
        img3: "https://m.media-amazon.com/images/I/51fES+YRTYL._AC_SY355_.jpg",
        title: "ADVENTURE NEO 1 EQ",
        description: "Una bici elettrica ideale per andare a lavoro e godersi le caratteristiche stradine di campagna",
        tag: "e-bike corsa",
        taglia: "s m l xl",
        colori: "+4",
        prezzo: "4.000,00",
        isDiscount: true,
        discountPrice: "3.900,00",
        isCompare: false,
        state: "usato",
    },
];

export default data;